name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout source code
        uses: actions/checkout@v4

      - name: â” Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - name: ğŸ“¦ Install npm
        run: npm ci

      - name: ğŸ— Global Install surge
        run: npm install -g surge

      - name: ğŸ­ Build npm
        run: npm run build

      - name: ğŸ’ Deploy surge
        run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
